# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Diaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='finished_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
