# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 19:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diaries', '0003_auto_20170524_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='friendly',
        ),
        migrations.AddField(
            model_name='diary',
            name='public',
            field=models.BooleanField(default=True, verbose_name='\u516c\u5f00'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(max_length=50, verbose_name='\u6807\u9898'),
        ),
    ]
