# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0017_auto_20160413_0107'),
        ('Diaries', '0004_auto_20170524_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='act_belonged',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Activities.Activity'),
        ),
    ]
