# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 02:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('BL', '\u7403\u7c7b'), ('KT', 'KTV'), ('TR', '\u65c5\u884c')], max_length=2)),
                ('start_time', models.DateTimeField()),
                ('due_time', models.DateTimeField()),
                ('personNum', models.PositiveSmallIntegerField()),
                ('active', models.NullBooleanField()),
                ('person_joined', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
