# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0004_auto_20160323_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='personNum',
            new_name='person_num_limit',
        ),
        migrations.AddField(
            model_name='activity',
            name='person_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
