# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0005_auto_20160324_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='person_count',
        ),
        migrations.AlterField(
            model_name='activity',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
