# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0006_auto_20160325_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='active',
        ),
    ]
