# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0012_auto_20160406_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='lng',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='lnt',
            field=models.FloatField(default=None, null=True),
        ),
    ]
