# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0013_auto_20160409_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='lnt',
        ),
        migrations.AddField(
            model_name='activity',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='place',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lng',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
