# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0014_auto_20160409_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='lat',
            new_name='dlat',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='lng',
            new_name='dlng',
        ),
        migrations.AddField(
            model_name='activity',
            name='slat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='slng',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
