# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0015_auto_20160410_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('SP', '\u8fd0\u52a8'), ('ET', '\u5a31\u4e50'), ('TR', '\u65c5\u884c')], max_length=2),
        ),
    ]
