# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='online',
            field=models.NullBooleanField(),
        ),
    ]
