# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_myuser_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_num',
            field=models.CharField(blank=True, default=None, max_length=15, unique=True),
        ),
    ]
