# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20160323_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nick_name',
            field=models.CharField(max_length=100),
        ),
    ]
