# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20160324_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nick_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
