# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 01:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_auto_20160324_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friend_each_other',
        ),
    ]
