# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_auto_20160327_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='o2s',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendship',
            name='s2o',
            field=models.BooleanField(default=False),
        ),
    ]
