# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_auto_20160407_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
