# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0021_auto_20160411_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile',
            field=models.ImageField(default='/media/profiles/default_profile.jpg', upload_to='profiles'),
        ),
    ]
