# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0022_auto_20160411_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='sam',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
