# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0002_auto_20160326_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rcver_preserved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='seder_preserved',
            field=models.BooleanField(default=True),
        ),
    ]
